name: Build Tweak

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y make clang git dpkg lld

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Build package
        run: |
          export THEOS=$HOME/theos
          make package

      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: rumble-deb
          path: packages/*.deb
